// packages/ui/react/src/components/button/Button.tsx
import type { ElementType, ReactElement } from 'react'
import './button.scss'
import { useButton, type ButtonProps } from './index'

/**
 * Button — рендерит кнопку с текстом из Core.
 *
 * - `tag` по умолчанию `button` (из TButton.defaultValues)
 * - `children` переопределяет `text`
 * - disabled → `disabled` у нативного button, иначе `aria-disabled`
 */
export function Button(props: ButtonProps): ReactElement | null {
	const { ref, forwardProps, state } = useButton(props)

	const { rendered, visible, tag, classes, disabled, text } = state

	if (!rendered) return null

	const Tag = tag as ElementType
	const isNativeButton = tag === 'button'

	const { className: userClassName, style: userStyle, ...restProps } = forwardProps
	const className = [classes.join(' '), userClassName].filter(Boolean).join(' ')
	const style = visible ? userStyle : { ...(userStyle ?? {}), display: 'none' }

	return (
		<Tag
			ref={ref}
			className={className}
			style={style}
			{...(isNativeButton
				? { disabled: disabled as boolean }
				: { 'aria-disabled': disabled as boolean })}
			{...restProps}
		>
			<span className="s-button__text">{props.children ?? text}</span>
		</Tag>
	)
}

// packages/ui/solid/src/components/button/Button.tsx
import { Show, children, createMemo, type JSX } from 'solid-js'
import { Dynamic } from 'solid-js/web'
import { setupButton } from './setup.component'
import type { ButtonProps } from './base.component'

/**
 * Button — рендерит кнопку с текстом из Core.
 *
 * - `tag` по умолчанию `button` (из TButton.defaultValues)
 * - `children` переопределяет `text`
 * - disabled → атрибут disabled у нативного button, иначе aria-disabled
 */
export function Button(props: ButtonProps): JSX.Element {
	const binding = setupButton(props)
	const state = binding.state

	const resolved = children(() => props.children)

	const attrs = createMemo(() => {
		const rest = binding.forwardProps()
		const isNativeButton = state.tag === 'button'

		return {
			...rest,
			class: [(state.classes as string[]).join(' '), rest.class].filter(Boolean).join(' '),
			style: { ...(rest.style as object), display: state.visible ? undefined : 'none' },
			...(isNativeButton
				? { disabled: state.disabled }
				: { 'aria-disabled': state.disabled || undefined }),
		}
	})

	return (
		<Show when={state.rendered}>
			<Dynamic component={state.tag as string} {...attrs()} ref={binding.ref}>
				<span class="s-button__text">
					<Show when={resolved()} fallback={state.text}>
						{resolved()}
					</Show>
				</span>
			</Dynamic>
		</Show>
	)
}
