// packages/ui/react/src/components/accordion/Accordion.tsx
import type { ReactElement } from 'react'
import { Elevate, hasSlot, relaySlot, renderSlot, toRootProps } from '../../adapter'
import { AccordionItem } from './item'
import { useSetupAccordion } from './setup.component'
import type { AccordionProps } from './base.component'

/**
 * Accordion — набор раскрывающихся секций. На корне — `attrs`, как у Vue.
 *
 * Секции — дети (`<Accordion.Item>`), а без детей — `shown` коллекции, по
 * `AccordionItem` на элемент. Слоты элементов статические и получают элемент
 * через scope: `item` — заголовок, `item-leading` и `item-trailing` — по его
 * краям, `item-leading-icon` и `item-trailing-icon` — стрелки, `item-content`
 * — содержимое панели. Отдельного `Accordion.Content` нет: панель лежит внутри
 * секции и отдельно от неё не существует.
 *
 * Проброс целиком: у каждого слота секции есть `item-<слот>`, и scope у него —
 * scope слота секции плюс сама секция. Заголовок со своим scope секция
 * получает функцией (`relaySlot`), а не готовым узлом, — иначе `text` и
 * `selected` до слота аккордеона не дошли бы.
 *
 * Всё содержимое — в слое лифта аккордеона (`Elevate`): секция, смонтированная
 * внутри, прочтёт движок и регистратор этого аккордеона и при коммите войдёт в
 * его коллекцию.
 */
export function Accordion(props: AccordionProps): ReactElement | null {
	const { ref, forwardProps, state, layer } = useSetupAccordion(props)

	const { rendered, shown, attrs } = state

	if (!rendered) return null

	return (
		<div {...toRootProps(ref, state, [attrs], forwardProps)}>
			<Elevate layer={layer}>
				{hasSlot(props.children)
					? renderSlot(props.children)
					: shown?.map((item) => (
							<AccordionItem
								key={item.uid}
								ctrl={item}
								leading-icon={renderSlot(props['item-leading-icon'], { item })}
								leading={renderSlot(props['item-leading'], { item })}
								header={relaySlot(props.item, { item })}
								trailing={renderSlot(props['item-trailing'], { item })}
								trailing-icon={renderSlot(props['item-trailing-icon'], { item })}
							>
								{renderSlot(props['item-content'], { item })}
							</AccordionItem>
						))}
			</Elevate>
		</div>
	)
}

// packages/ui/vue/src/components/accordion/Accordion.vue
<script lang="ts">
import { AccordionItem } from './item'
import SetupAccordion from './setup.component'

export default { ...SetupAccordion, components: { AccordionItem } }
</script>

<template>
	<div ref="rootElement" v-if="rendered" v-show="visible" :class="classes" v-bind="attrs">
		<slot>
			<!--
				Слоты элементов статические и получают элемент через scope —
				динамические имена резолвит только Vue (см. Tabs.vue). Проброс
				целиком: у каждого слота секции есть `item-<слот>`, и его scope —
				scope слота секции плюс сама секция. Заголовок секции (`header`) —
				`item`.

				`item-content` — содержимое раскрывающейся панели. Отдельного
				компонента `Accordion.Content` нет: панель лежит внутри элемента и
				отдельно от него не существует, поэтому она остаётся слотом.

				Стрелки секция рисует сама и по наличию слота решает, стоять ли
				обёртке стрелки на этой стороне, — поэтому их слоты отдаются ей,
				только когда заданы аккордеону.
			-->
			<AccordionItem v-for="item in shown" :key="item.uid" :ctrl="item">
				<template v-if="$slots['item-leading-icon']" #leading-icon>
					<slot name="item-leading-icon" :item="item" />
				</template>
				<template #leading>
					<slot name="item-leading" :item="item" />
				</template>
				<template #header="{ text, selected }">
					<slot name="item" :item="item" :text="text" :selected="selected" />
				</template>
				<template #trailing>
					<slot name="item-trailing" :item="item" />
				</template>
				<template v-if="$slots['item-trailing-icon']" #trailing-icon>
					<slot name="item-trailing-icon" :item="item" />
				</template>
				<slot name="item-content" :item="item" />
			</AccordionItem>
		</slot>
	</div>
</template>
