// packages/ui/react/src/components/list-box/item/Item.tsx
import type { ElementType, ReactElement } from 'react'
import {
	renderSlot,
	roleIcon,
	toAriaProps,
	toControlAttrs,
	toRootForward,
	toRootProps,
} from '../../../adapter'
import { Button } from '../../button'
import { Icon } from '../../icon'
import { useSetupListBoxItem } from './setup.component'
import type { ListBoxItemAttributes, ListBoxItemProps } from './base.component'

/**
 * ListBoxItem — элемент списка: корень по `tag` (по умолчанию `div`) и строка
 * внутри — `Button`, как у Vue.
 *
 * Наборы ядра стоят на двух элементах. Корень несёт `dataset`, `attrs` и место
 * в коллекции (`order`): тема читает `data-content-fit` с него. Строка несёт
 * `aria` и тот же `dataset` — выбор и подсветку тема красит на `.s-button`.
 * Атрибуты потребителя делятся так же, как у Vue: класс и стиль — корню,
 * остальное — строке, поверх её наборов: `tabindex="-1"` элемента перекрывает
 * `tabindex="0"`, который кнопка на `div` ставит себе сама.
 *
 * Тег строки фиксирован (`div`), а не берётся из `tag` элемента: `tag` — тег
 * корня, под фиксированный тег строки написан `TListBoxItem._ariaTag`.
 *
 * Клик выбирает через `adapters.list.choose()`, а не `selection.toggle()`:
 * выключенному элементу отказывает список, тем же путём, что и клавиатура.
 * Клик потребителя приходит после выбора — как у Vue, где слушатели
 * складываются.
 *
 * Обёртка отметки рисуется, пока `indicator` не `none`, — и у невыбранных
 * тоже: она резервирует место. Иконка внутри — только у выбранного, слот
 * `indicator-icon` подменяет её. `aria-hidden`: состояние скринридеру
 * объявляет `aria-selected`, второй источник того же факта дал бы двойное
 * объявление.
 */
export function ListBoxItem(props: ListBoxItemProps): ReactElement | null {
	const { ref, forwardProps, state, context } = useSetupListBoxItem(props)

	const {
		rendered,
		tag,
		text,
		view,
		disabled,
		size,
		variant,
		selected,
		indicator,
		aria,
		dataset,
		attrs,
	} = state

	if (!rendered) return null

	const Tag = tag as ElementType
	const chosen = selected ?? false
	const { onClick, ...row } = toControlAttrs<ListBoxItemAttributes>(forwardProps)

	const mark = (
		<span className="s-list-box-item__indicator" aria-hidden="true">
			{renderSlot(props['indicator-icon'], { selected: chosen }) ??
				(chosen ? (
					<Icon embedded="list-box.indicator" tag={roleIcon('check')} size={size} />
				) : null)}
		</span>
	)

	return (
		<Tag {...toRootProps(ref, state, [dataset, attrs], toRootForward(forwardProps))}>
			<Button
				embedded="list-box.row"
				tag="div"
				view={view}
				disabled={disabled}
				size={size}
				variant={variant}
				{...toAriaProps(aria)}
				{...toAriaProps(dataset)}
				{...row}
				onClick={(event) => {
					context?.adapters.list.choose()
					onClick?.(event)
				}}
				leading={
					<>
						{indicator === 'start' ? mark : null}
						{renderSlot(props.leading)}
					</>
				}
				trailing={
					<>
						{renderSlot(props.trailing)}
						{indicator === 'end' ? mark : null}
					</>
				}
			>
				{renderSlot(props.children, { text: text ?? '', selected: chosen }) ?? text}
			</Button>
		</Tag>
	)
}

// packages/ui/vue/src/components/select/item/Item.vue
<script lang="ts">
import { Icon } from '../../icon'
import { Button } from '../../button'
import SetupSelectItem from './setup.component'

/**
 * Вся ARIA опции — на вложенном `Button`, строке опции: `role="option"` от
 * ядра, `id` и `aria-selected` от расширения коллекции. Один набор, шаблону не
 * нужно знать, кто в него писал. Узел с ролью один, как у Tabs, Accordion,
 * ListBox и Tags: набор опции ложится поверх того, что `Button` пишет себе
 * сам, — `role="option"` перекрывает `role="button"`, `tabindex="-1"` выводит
 * строку из обхода (фокус остаётся на поле), а `aria-disabled` у них один и
 * тот же.
 *
 * Тег строки фиксирован (`tag="span"`), а не берётся из `tag` элемента:
 * `tag` — тег корня (`TComponentView`), и рисует по нему корень
 * `<component :is>`. Под фиксированный тег строки написан и
 * `TSelectItem._ariaTag` — он решает, писать ли `aria-disabled`.
 *
 * `dataset` — то же состояние для темы (`data-selected`, `data-highlighted`),
 * тоже готовым набором: выбор пишет расширение выборки, подсветку —
 * `TListItemPlugin`. ARIA для скринридера, `data-*` для стилей; смешивать
 * нельзя, иначе правка доступности ломает вид.
 *
 * `dataset` биндится дважды — на обёртку и на `Button`: фон при hover/
 * подсветке/выборе тема рисует на самой кнопке и читает `data-highlighted` /
 * `data-selected` с неё. То же устройство, что у `ListBoxItem`.
 *
 * Вида у строки в разметке нет: значения вида объявляет тема, и библиотека их
 * не знает. Строку опции тема красит по контексту (`.s-select-item`).
 *
 * Выбранность и подсветка — разные вещи: подсветка живёт, только пока панель
 * открыта, и в значение не попадает.
 *
 * Пояснение в `<script>`, а не комментарием над корнем: в dev-режиме
 * компилятор SFC комментарии сохраняет, и такой комментарий сделал бы
 * компонент многокорневым — см. `Select.vue`.
 *
 * Отметка выбранного (`indicator`) рисуется внутри слотов кнопки: обёртка
 * стоит, пока сторона задана, — она резервирует место, чтобы строка не прыгала
 * при выборе; иконка внутри появляется только у выбранной опции. Обёртка
 * `aria-hidden`: состояние скринридеру объявляет `aria-selected`.
 */
export default { ...SetupSelectItem, components: { Icon, Button } }
</script>

<template>
	<component
		ref="rootElement"
		:is="tag"
		v-if="rendered"
		v-show="visible"
		:class="classes"
		:style="{ order: order }"
		@click="context?.adapters.select.choose()"
		v-bind="{ ...dataset, ...containerAttrs, ...attrs }"
	>
		<Button
			embedded="select.row"
			tag="span"
			:size="size"
			:variant="variant"
			:disabled="resolvedDisabled"
			tabindex="-1"
			v-bind="{ ...aria, ...dataset, ...controlAttrs }"
		>
			<template #leading>
				<span
					v-if="indicator === 'start'"
					class="s-select-item__indicator"
					aria-hidden="true"
				>
					<slot name="indicator-icon" :selected="selected">
						<Icon
							embedded="select.indicator"
							v-if="selected"
							:tag="indicatorIconTag"
							:size="size"
						/>
					</slot>
				</span>
				<slot name="leading" />
			</template>

			<slot :text="text" :selected="selected">
				{{ text }}
			</slot>

			<template #trailing>
				<slot name="trailing" />
				<span
					v-if="indicator === 'end'"
					class="s-select-item__indicator"
					aria-hidden="true"
				>
					<slot name="indicator-icon" :selected="selected">
						<Icon
							embedded="select.indicator"
							v-if="selected"
							:tag="indicatorIconTag"
							:size="size"
						/>
					</slot>
				</span>
			</template>
		</Button>
	</component>
</template>
