// packages/ui/react/src/types.ts
/**
 * Общие типы для React-адаптера @soldy/ui-react.
 */

import type { HTMLAttributes, ReactNode } from 'react'
import type { IEntity } from '@soldy/core'
import type {
	IComponentDescriptor,
	DescriptorAllProps,
	DescriptorSlots,
	DescriptorAllEvents,
	TCallbackEventProps,
	TSlotProps,
} from '@soldy/setup'

/**
 * Базовые props React-компонента: core-props + `ctrl` — готовый core-инстанс
 * (если не передан, создаётся из Ctor).
 *
 * `children` здесь нет: слот по умолчанию объявлен в контракте компонента
 * наравне с остальными и приходит из SlotProps.
 */
export type TReactComponentProps<TCoreProps, TInstance extends IEntity = IEntity> = TCoreProps & {
	ctrl?: TInstance
	/**
	 * Имя места, если компонент — деталь разметки другого компонента soldy
	 * (`tags.close`). Ставит разметка библиотеки, а не потребитель: по нему
	 * `usePlugins` со `scope: 'own'` пропускает вложенный компонент.
	 */
	embedded?: string
}

/** Событийные пропсы компонента из дескриптора (core + плагины). */
export type EventProps<TDescriptorFn extends (...args: any[]) => IComponentDescriptor> =
	TCallbackEventProps<DescriptorAllEvents<TDescriptorFn>>

/**
 * Слоты компонента из дескриптора: `default` становится `children`,
 * остальные сохраняют имена. Слот со scope принимает и функцию.
 */
export type SlotProps<TDescriptorFn extends (...args: any[]) => IComponentDescriptor> = TSlotProps<
	DescriptorSlots<TDescriptorFn>,
	ReactNode
>

/** Props headless-компонента: core props + события + слоты + служебные поля. */
export type UseProps<
	TDescriptorFn extends (...args: any[]) => IComponentDescriptor,
	TInstance extends IEntity = IEntity,
	TEvents extends object = EventProps<TDescriptorFn>,
> = TReactComponentProps<DescriptorAllProps<TDescriptorFn>, TInstance> &
	TEvents &
	SlotProps<TDescriptorFn>

/**
 * Props DOM-компонента: UseProps + HTML-атрибуты без конфликтов с core props.
 *
 * `children` из HTMLAttributes исключён: он объявлен `ReactNode`, и пересечение
 * со scoped-слотом (`ReactNode | ((scope) => ReactNode)`) убило бы форму-функцию.
 */
export type UseDomProps<
	TDescriptorFn extends (...args: any[]) => IComponentDescriptor,
	TInstance extends IEntity = IEntity,
	TEvents extends object = EventProps<TDescriptorFn>,
> = UseProps<TDescriptorFn, TInstance, TEvents> &
	Omit<HTMLAttributes<HTMLElement>, keyof DescriptorAllProps<TDescriptorFn> | 'children'>

// packages/ui/solid/src/types.ts
/**
 * Общие типы Solid-адаптера @soldy/ui-solid.
 */

import type { JSX } from 'solid-js'
import type { IEntity } from '@soldy/core'
import type {
	IComponentDescriptor,
	DescriptorAllProps,
	DescriptorSlots,
	DescriptorAllEvents,
	TCallbackEventProps,
	TSlotProps,
} from '@soldy/setup'

/**
 * Базовые props Solid-компонента: core-props + `ctrl` — готовый core-инстанс
 * (если не передан, создаётся из Ctor).
 *
 * `children` здесь нет: слот по умолчанию объявлен в контракте компонента
 * наравне с остальными и приходит из SlotProps.
 */
export type TSolidComponentProps<TCoreProps, TInstance extends IEntity = IEntity> = TCoreProps & {
	ctrl?: TInstance
	/**
	 * Имя места, если компонент — деталь разметки другого компонента soldy
	 * (`tags.close`). Ставит разметка библиотеки, а не потребитель: по нему
	 * `usePlugins` со `scope: 'own'` пропускает вложенный компонент.
	 */
	embedded?: string
}

/** Событийные пропы компонента из дескриптора (core + плагины). */
export type EventProps<TDescriptorFn extends (...args: any[]) => IComponentDescriptor> =
	TCallbackEventProps<DescriptorAllEvents<TDescriptorFn>>

/**
 * Слоты компонента из дескриптора: `default` становится `children`,
 * остальные сохраняют имена. Слот со scope принимает и функцию.
 */
export type SlotProps<TDescriptorFn extends (...args: any[]) => IComponentDescriptor> = TSlotProps<
	DescriptorSlots<TDescriptorFn>,
	JSX.Element
>

/** Props headless-слоя: core props + события + слоты + служебные поля. */
export type UseProps<
	TDescriptorFn extends (...args: any[]) => IComponentDescriptor,
	TInstance extends IEntity = IEntity,
	TEvents extends object = EventProps<TDescriptorFn>,
> = TSolidComponentProps<DescriptorAllProps<TDescriptorFn>, TInstance> &
	TEvents &
	SlotProps<TDescriptorFn>

/** Props DOM-компонента: UseProps + HTML-атрибуты без конфликтов с core props. */
export type UseDomProps<
	TDescriptorFn extends (...args: any[]) => IComponentDescriptor,
	TInstance extends IEntity = IEntity,
	TEvents extends object = EventProps<TDescriptorFn>,
> = UseProps<TDescriptorFn, TInstance, TEvents> &
	Omit<JSX.HTMLAttributes<HTMLElement>, keyof DescriptorAllProps<TDescriptorFn> | 'children'>
