// packages/ui/solid/demo/common/Properties.tsx
import { For, Match, Show, Switch, type JSX } from 'solid-js'
import PropertyField from './PropertyField'

/**
 * Универсальный компонент Properties для демо playground'ов.
 * Автоматически генерирует поля на основе схемы свойств.
 */

export type TPropertyType = 'boolean' | 'string' | 'number' | 'select'

export interface IPropertyDefinition {
	type: TPropertyType
	default?: any
	options?: Array<{ value: any; label?: string }> | any[]
	placeholder?: string
}

export type TPropertiesSchema = Record<string, IPropertyDefinition>

type PropertiesProps = {
	value: Record<string, any>
	schema: TPropertiesSchema
	onChange: (value: Record<string, any>) => void
	onShow?: () => void
	onHide?: () => void
}

function optionValue(option: any) {
	return typeof option === 'object' && option !== null ? option.value : option
}

function optionLabel(option: any) {
	return typeof option === 'object' && option !== null && option.label
		? option.label
		: String(option)
}

export default function Properties(props: PropertiesProps): JSX.Element {
	const update = (key: string, next: any) => props.onChange({ ...props.value, [key]: next })
	const getValue = (key: string) => props.value[key] ?? props.schema[key]?.default

	return (
		<div class="properties-panel">
			<For each={Object.entries(props.schema)}>
				{([key, def]) => (
					<Switch>
						<Match when={def.type === 'boolean'}>
							<PropertyField label={key}>
								<input
									type="checkbox"
									class="properties-panel__checkbox"
									checked={getValue(key)}
									onChange={(e) => update(key, e.currentTarget.checked)}
								/>
							</PropertyField>
						</Match>

						<Match when={def.type === 'string' || def.type === 'number'}>
							<PropertyField label={key}>
								<input
									type={def.type === 'number' ? 'number' : 'text'}
									class="properties-panel__input"
									placeholder={def.placeholder}
									value={getValue(key)}
									onInput={(e) =>
										update(
											key,
											def.type === 'number'
												? e.currentTarget.valueAsNumber
												: e.currentTarget.value,
										)
									}
								/>
							</PropertyField>
						</Match>

						<Match when={def.type === 'select' && def.options}>
							<PropertyField label={key}>
								<select
									class="properties-panel__select"
									value={getValue(key)}
									onChange={(e) => update(key, e.currentTarget.value)}
								>
									<For each={def.options}>
										{(option) => <option value={optionValue(option)}>{optionLabel(option)}</option>}
									</For>
								</select>
							</PropertyField>
						</Match>
					</Switch>
				)}
			</For>

			<Show when={'visible' in props.schema}>
				<PropertyField label="actions">
					<div class="properties-panel__actions">
						<button
							class="properties-panel__button"
							onClick={() => {
								update('visible', true)
								props.onShow?.()
							}}
						>
							Show
						</button>
						<button
							class="properties-panel__button"
							onClick={() => {
								update('visible', false)
								props.onHide?.()
							}}
						>
							Hide
						</button>
					</div>
				</PropertyField>
			</Show>
		</div>
	)
}

// packages/ui/angular/demo/app/common/properties.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	EventEmitter,
	Input,
	Output,
} from '@angular/core'
import { PropertyFieldComponent } from './property-field.component'

export type TPropertyType = 'boolean' | 'string' | 'number' | 'select'

export interface IPropertyDefinition {
	type: TPropertyType
	default?: any
	options?: any[]
	placeholder?: string
}

export type TPropertiesSchema = Record<string, IPropertyDefinition>

/**
 * Универсальная панель свойств для playground'ов.
 * Автоматически генерирует поля на основе схемы (schema-driven).
 */
@Component({
	selector: 'demo-properties',
	standalone: true,
	imports: [PropertyFieldComponent],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<div class="properties-panel">
			@for (entry of entries; track entry.key) {
				@switch (entry.def.type) {
					@case ('boolean') {
						<demo-property-field [label]="entry.key">
							<input
								type="checkbox"
								class="properties-panel__checkbox"
								[checked]="entry.value"
								(change)="update(entry.key, $any($event.target).checked)"
							/>
						</demo-property-field>
					}
					@case ('string') {
						<demo-property-field [label]="entry.key">
							<input
								type="text"
								class="properties-panel__input"
								[value]="entry.value"
								[placeholder]="entry.def.placeholder"
								(input)="update(entry.key, $any($event.target).value)"
							/>
						</demo-property-field>
					}
					@case ('number') {
						<demo-property-field [label]="entry.key">
							<input
								type="number"
								class="properties-panel__input"
								[value]="entry.value"
								(input)="update(entry.key, $any($event.target).valueAsNumber)"
							/>
						</demo-property-field>
					}
					@case ('select') {
						<demo-property-field [label]="entry.key">
							<select
								class="properties-panel__select"
								[value]="entry.value"
								(change)="update(entry.key, $any($event.target).value)"
							>
								@for (option of entry.def.options; track $index) {
									<option [value]="optionValue(option)">{{ optionLabel(option) }}</option>
								}
							</select>
						</demo-property-field>
					}
				}
			}

			@if (hasVisibility) {
				<div class="properties-panel__actions">
					<button class="properties-panel__action-btn" (click)="showRequested.emit()">
						Show
					</button>
					<button class="properties-panel__action-btn" (click)="hideRequested.emit()">
						Hide
					</button>
				</div>
			}
		</div>
	`,
})
export class PropertiesComponent {
	@Input() schema: TPropertiesSchema = {}
	@Input() value: Record<string, any> = {}

	@Output() changed = new EventEmitter<Record<string, any>>()
	@Output() showRequested = new EventEmitter<void>()
	@Output() hideRequested = new EventEmitter<void>()

	protected get entries() {
		return Object.entries(this.schema).map(([key, def]) => ({
			key,
			def,
			value: this.value[key] ?? def.default,
		}))
	}

	protected get hasVisibility(): boolean {
		return 'visible' in this.schema
	}

	protected update(key: string, nextValue: any): void {
		this.changed.emit({ ...this.value, [key]: nextValue })
	}

	protected optionValue(option: any): any {
		return typeof option === 'object' && option !== null ? option.value : option
	}

	protected optionLabel(option: any): string {
		if (typeof option === 'object' && option !== null) {
			return option.label ?? String(option.value)
		}

		return String(option)
	}
}
