// packages/ui/react/demo/common/PanelDemo.tsx
import type { ReactNode } from 'react'

type PanelDemoProps = {
	title?: string
	info?: string
	children: ReactNode
}

export default function PanelDemo({ title, info, children }: PanelDemoProps) {
	return (
		<div className="panel-demo">
			{title && <h3 className="panel-demo__title">{title}</h3>}
			<div className="panel-demo__content">{children}</div>
			{info && <div className="panel-demo__info">{info}</div>}
		</div>
	)
}

// packages/ui/solid/demo/common/PanelDemo.tsx
import { Show, type JSX } from 'solid-js'

type PanelDemoProps = {
	title?: string
	info?: string
	children: JSX.Element
}

export default function PanelDemo(props: PanelDemoProps): JSX.Element {
	return (
		<div class="panel-demo">
			<Show when={props.title}>
				<h3 class="panel-demo__title">{props.title}</h3>
			</Show>
			<div class="panel-demo__content">{props.children}</div>
			<Show when={props.info}>
				<div class="panel-demo__info">{props.info}</div>
			</Show>
		</div>
	)
}
