// packages/ui/vue/src/components/accordion/item/Item.vue
<script lang="ts">
import { Icon } from '../../icon'
import { Button } from '../../button'
import SetupAccordionItem from './setup.component'

export default { ...SetupAccordionItem, components: { Icon, Button } }
</script>

<template>
	<component
		ref="rootElement"
		:is="tag"
		v-if="rendered"
		v-show="visible"
		:class="classes"
		:style="{ order: order }"
		v-bind="{ ...dataset, ...containerAttrs, ...attrs }"
	>
		<!--
			Связка «заголовок ↔ панель» приходит из item-адаптера расширения
			`content`: `aria-controls` заголовка и `id` панели — один и тот же
			идентификатор, поэтому считаются в одном месте.

			`aria-selected` с обёртки убран: у неё нет роли, и для скринридера
			он ничего не значил. Но тема раскрывала панель селектором
			`.s-accordion-item[aria-selected='true']`, поэтому обёртка отдаёт то
			же состояние как `data-selected`: ARIA — для скринридера, `data-*` —
			для CSS. Иначе ARIA нельзя починить, не сломав вид.

			Оба набора приходят готовыми из ядра — `dataset` на обёртку,
			`aria` на заголовок. В шаблоне не осталось ни одного вычисления
			состояния: иначе его пришлось бы повторить в пяти других адаптерах.

			Стрелка — в обёртке, и класс стрелки на обёртке, а не на иконке:
			тема поворачивает стрелку раскрытой секции по
			`.s-accordion-item__arrow`, и иконка, подменённая слотом
			`leading-icon` или `trailing-icon`, поворачивается так же. Поставь
			класс на `Icon` — и подменённая стрелка перестала бы поворачиваться,
			причём молча (как `s-select__arrow` у Select). Обёртка стоит, пока на
			её стороне стрелка по умолчанию или задан слот.
		-->
		<Button
			embedded="accordion.header"
			class="s-accordion-item__header"
			:view="view"
			:disabled="disabled"
			:size="size"
			:variant="variant"
			@click="context?.adapters.selection.toggle()"
			v-bind="{ ...aria, ...controlAttrs }"
		>
			<template #leading>
				<span
					v-if="arrowPlacement === 'start' || $slots['leading-icon']"
					class="s-accordion-item__arrow"
				>
					<slot name="leading-icon">
						<Icon
							embedded="accordion.arrow"
							v-if="arrowPlacement === 'start'"
							:tag="arrowIconTag"
							:size="size"
						/>
					</slot>
				</span>
				<slot name="leading" />
			</template>

			<slot name="header" :text="text" :selected="selected">
				{{ text }}
			</slot>

			<template #trailing>
				<slot name="trailing" />
				<span
					v-if="arrowPlacement === 'end' || $slots['trailing-icon']"
					class="s-accordion-item__arrow"
				>
					<slot name="trailing-icon">
						<Icon
							embedded="accordion.arrow"
							v-if="arrowPlacement === 'end'"
							:tag="arrowIconTag"
							:size="size"
						/>
					</slot>
				</span>
			</template>
		</Button>

		<div class="s-accordion-item__body">
			<div class="s-accordion-item__content" v-bind="contentAria">
				<slot />
			</div>
		</div>
	</component>
</template>

// packages/ui/react/src/components/accordion/item/Item.tsx
import type { ElementType, ReactElement, ReactNode } from 'react'
import {
	hasSlot,
	renderSlot,
	roleIcon,
	toAriaProps,
	toControlAttrs,
	toRootForward,
	toRootProps,
} from '../../../adapter'
import { Button } from '../../button'
import { Icon } from '../../icon'
import { useSetupAccordionItem } from './setup.component'
import type { AccordionItemAttributes, AccordionItemProps } from './base.component'

/**
 * AccordionItem — секция: корень по `tag` (по умолчанию `div`), внутри
 * заголовок — `Button` — и панель, как у Vue.
 *
 * Наборы ядра стоят там же, где у Vue. Корень несёт `dataset`, `attrs` и место
 * в коллекции (`order`): тема раскрывает панель по `data-selected` на нём.
 * Заголовок несёт `aria` — `aria-expanded` пишет коллекция, сторону связки с
 * панелью (`id`, `aria-controls`) — плагин секции. Панель несёт набор секции
 * `contentAria` (`role="region"`, `id`, `aria-labelledby`): своего экземпляра
 * у неё нет. Атрибуты потребителя делятся, как у ListBox.Item: класс и стиль —
 * корню, остальное — заголовку, поверх его `aria`.
 *
 * Клик заголовка раскрывает или сворачивает секцию, потом зовёт клик
 * потребителя — как у Vue, где слушатели складываются.
 *
 * Стрелка — по краю заголовка со стороны `arrowPlacement`. Слоты
 * `leading-icon` и `trailing-icon` подменяют её, по умолчанию она — иконка
 * пакета по роли `arrowRight`. Стрелка — в обёртке, и класс стрелки на
 * обёртке, а не на иконке: тема поворачивает стрелку раскрытой секции по
 * `.s-accordion-item__arrow`, и подменённая иконка поворачивается так же.
 * Обёртка стоит, пока на её стороне стрелка по умолчанию или задан слот.
 */
export function AccordionItem(props: AccordionItemProps): ReactElement | null {
	const { ref, forwardProps, state, context } = useSetupAccordionItem(props)

	const {
		rendered,
		tag,
		text,
		view,
		disabled,
		size,
		variant,
		selected,
		arrowPlacement,
		contentAria,
		aria,
		dataset,
		attrs,
	} = state

	if (!rendered) return null

	const Tag = tag as ElementType
	const { onClick, ...header } = toControlAttrs<AccordionItemAttributes>(forwardProps)

	/** Стрелка стороны: слот, а без него — иконка, если стрелка на этой стороне. */
	const arrowAt = (side: 'start' | 'end', slot: ReactNode) =>
		hasSlot(slot) || arrowPlacement === side ? (
			<span className="s-accordion-item__arrow">
				{hasSlot(slot) ? (
					renderSlot(slot)
				) : (
					<Icon embedded="accordion.arrow" tag={roleIcon('arrowRight')} size={size} />
				)}
			</span>
		) : null

	return (
		<Tag {...toRootProps(ref, state, [dataset, attrs], toRootForward(forwardProps))}>
			<Button
				embedded="accordion.header"
				className="s-accordion-item__header"
				view={view}
				disabled={disabled}
				size={size}
				variant={variant}
				{...toAriaProps(aria)}
				{...header}
				onClick={(event) => {
					context?.adapters.selection.toggle()
					onClick?.(event)
				}}
				leading={
					<>
						{arrowAt('start', props['leading-icon'])}
						{renderSlot(props.leading)}
					</>
				}
				trailing={
					<>
						{renderSlot(props.trailing)}
						{arrowAt('end', props['trailing-icon'])}
					</>
				}
			>
				{renderSlot(props.header, { text: text ?? '', selected: selected ?? false }) ??
					text}
			</Button>
			<div className="s-accordion-item__body">
				<div className="s-accordion-item__content" {...toAriaProps(contentAria)}>
					{renderSlot(props.children)}
				</div>
			</div>
		</Tag>
	)
}
