// packages/ui/vue/demo/playgrounds/ComponentView.vue
<script setup lang="ts">
import { ref } from 'vue'
import PlaygroundLayout from './../layouts/PlaygroundLayout.vue'
import type { EventLogEntry } from '../common/EventLog.vue'
import Properties from './../common/Properties.vue'
import type { TPropertiesSchema } from './../common/Properties.vue'
import PropsDemo from './../components/component-view/Component.vue'
import InstanceDemo from './../components/component-view/Instance.vue'
import SlotsDemo from './../components/component-view/Slots.vue'
import { HTML_TAGS } from '../common/items'

const emit = defineEmits<{
	log: [entry: EventLogEntry]
}>()

// Схема свойств для ComponentView
const propertiesSchema: TPropertiesSchema = {
	visible: { type: 'boolean', default: true },
	rendered: { type: 'boolean', default: true },
	tag: { type: 'select', default: 'div', options: HTML_TAGS },
}

// Component properties state
const componentProps = ref({
	visible: true,
	rendered: true,
	tag: 'div',
})

// Ref для Instance demo
const instanceDemoRef = ref<InstanceType<typeof InstanceDemo>>()

const handleShow = () => {
	instanceDemoRef.value?.show()
}

const handleHide = () => {
	instanceDemoRef.value?.hide()
}
</script>

<template>
	<PlaygroundLayout title="ComponentView Playground">
		<template #properties>
			<Properties
				v-model="componentProps"
				:schema="propertiesSchema"
				@show="handleShow"
				@hide="handleHide"
			/>
		</template>

		<template #props-demo>
			<PropsDemo v-bind="componentProps" @log="emit('log', $event)" />
		</template>

		<!-- <template #instance-demo>
			<InstanceDemo
				ref="instanceDemoRef"
				v-bind="componentProps"
				@log="emit('log', $event)"
			/>
		</template>

		<template #slots-demo>
			<SlotsDemo v-bind="componentProps" />
		</template> -->
	</PlaygroundLayout>
</template>

// packages/ui/react/demo/playgrounds/ComponentView.tsx
import { useRef, useState } from 'react'
import PlaygroundLayout from '../layouts/PlaygroundLayout'
import Properties from '../common/Properties'
import type { TPropertiesSchema } from '../common/Properties'
import PropsDemo from '../components/component-view/Component'
import InstanceDemo, {
	type ComponentViewInstanceDemoHandle,
} from '../components/component-view/Instance'
import SlotsDemo from '../components/component-view/Slots'
import { HTML_TAGS } from '../common/items'
import type { EventLogEntry } from '../common/EventLog'

type ComponentViewPlaygroundProps = {
	onLog: (entry: EventLogEntry) => void
}

const propertiesSchema: TPropertiesSchema = {
	visible: { type: 'boolean', default: true },
	rendered: { type: 'boolean', default: true },
	tag: { type: 'select', default: 'div', options: HTML_TAGS },
}

type ComponentViewProps = {
	visible: boolean
	rendered: boolean
	tag: string
}

export default function ComponentViewPlayground({ onLog }: ComponentViewPlaygroundProps) {
	const [componentProps, setComponentProps] = useState<ComponentViewProps>({
		visible: true,
		rendered: true,
		tag: 'div',
	})

	const instanceDemoRef = useRef<ComponentViewInstanceDemoHandle>(null)

	const handleShow = () => instanceDemoRef.current?.show()
	const handleHide = () => instanceDemoRef.current?.hide()

	return (
		<PlaygroundLayout
			title="ComponentView Playground"
			properties={
				<Properties
					value={componentProps}
					schema={propertiesSchema}
					onChange={setComponentProps}
					onShow={handleShow}
					onHide={handleHide}
				/>
			}
			propsDemo={<PropsDemo {...componentProps} onLog={onLog} />}
			instanceDemo={
				<InstanceDemo ref={instanceDemoRef} {...componentProps} onLog={onLog} />
			}
			slotsDemo={<SlotsDemo {...componentProps} />}
		/>
	)
}
