// packages/ui/react/src/components/input/Input.tsx
import type { ElementType, ReactElement } from 'react'
import {
	NativeInput,
	hasSlot,
	renderSlot,
	roleIcon,
	toAriaProps,
	toControlAttrs,
	toRootLayout,
} from '../../adapter'
import { Button } from '../button'
import { Icon } from '../icon'
import { useSetupInput } from './setup.component'
import type { InputAttributes, InputProps } from './base.component'

/**
 * Input — текстовое поле: корень по `tag` (по умолчанию `div`) и `<input>`
 * внутри, по сторонам — слоты `leading` и `trailing`.
 *
 * Наборы ядра стоят на разных элементах: `attrs` (`dir`) — на корне, `aria` —
 * на `<input>`. Нативные `disabled`, `readonly` и `required` поля проводит
 * разметка, поэтому ARIA-дублей ядро рядом с ними не пишет. Атрибуты
 * потребителя делятся так же, как у Vue: класс и стиль — корню, всё
 * остальное — полю, поверх его атрибутов.
 *
 * Текст поля ведёт ядро: в ядро его несёт плагин ввода, в узел — поле
 * адаптера (`NativeInput`), контролируемого поля React здесь нет.
 *
 * Слоты стоят по сторонам поля, а не внутри него: `<input>` детей не имеет.
 * Обёртка слота рисуется, только если в неё есть что положить; содержимое
 * получает сам инстанс поля — кнопке рядом с полем нужны его значение и
 * методы.
 *
 * Кнопка очистки — первой в обёртке у конца поля, перед `trailing`, как у
 * Vue: по `clearable`, выключена вместе с полем, `readonly` её не гасит. Имя
 * ядро собирает с именем поля (`clearAria`), очищает команда поля `clear`.
 * Своя кнопка — слот `clear` с командой в scope: заменяет встроенную целиком.
 *
 * Очищает кнопка по `onActionClick` — нативному клику её `TActionPlugin` — и
 * гасит всплытие у нативного события, как крестик таба: синтетический
 * `stopPropagation` React опоздал бы — к нему событие уже прошло корни
 * предков, а select-only Select открывает панель кликом по корню. Vue гасит
 * то же `@click.stop`.
 */
export function Input(props: InputProps): ReactElement | null {
	const { ctrl, ref, forwardProps, state } = useSetupInput(props)

	const {
		rendered,
		tag,
		attrs,
		aria,
		id,
		value,
		name,
		disabled,
		readonly,
		required,
		placeholder,
		size,
		clearable,
		clearAria,
	} = state

	if (!rendered) return null

	const Tag = tag as ElementType
	const trailing = clearable === true || hasSlot(props.clear) || hasSlot(props.trailing)

	return (
		<Tag ref={ref} {...toRootLayout(state, forwardProps)} {...toAriaProps(attrs)}>
			{hasSlot(props.leading) ? (
				<div className="s-input__leading">{renderSlot(props.leading, { ctrl })}</div>
			) : null}
			<NativeInput
				type="text"
				id={id}
				name={name}
				disabled={disabled}
				readOnly={readonly}
				required={required}
				placeholder={placeholder}
				{...toAriaProps(aria)}
				{...toControlAttrs<InputAttributes>(forwardProps)}
				live={{ value }}
			/>
			{trailing ? (
				<div className="s-input__trailing">
					{renderSlot(props.clear, { clear: ctrl.clear }) ??
						(clearable === true ? (
							<Button
								embedded="input.clear"
								className="s-input__clear"
								size={size}
								disabled={disabled}
								{...toAriaProps(clearAria)}
								onActionClick={(event) => {
									event.stopPropagation()
									ctrl.clear()
								}}
							>
								<Icon
									embedded="input.clear-icon"
									tag={roleIcon('close')}
									size={size}
								/>
							</Button>
						) : null)}
					{renderSlot(props.trailing, { ctrl })}
				</div>
			) : null}
		</Tag>
	)
}

// packages/ui/vue/src/components/input/Input.vue
<script lang="ts">
import { Button } from '../button'
import { Icon } from '../icon'
import SetupInput from './setup.component'

export default { ...SetupInput, components: { Button, Icon } }
</script>

<template>
	<component
		ref="rootElement"
		:is="tag"
		v-if="rendered"
		v-show="visible"
		:class="classes"
		v-bind="{ ...attrs, ...containerAttrs }"
	>
		<!--
			Корень рисуется по `tag`, по умолчанию `div`: `tag` — всегда тег
			корня, и по нему же ядро решает, есть ли у корня нативный
			`disabled`.
		-->
		<div v-if="$slots.leading" class="s-input__leading">
			<slot name="leading" :ctrl="ctrl"> </slot>
		</div>
		<input
			type="text"
			:id="id"
			:value="value"
			:name="name"
			:disabled="disabled"
			:readonly="readonly"
			:required="required"
			:placeholder="placeholder"
			v-bind="{ ...aria, ...controlAttrs }"
		/>
		<!--
			Обёртка у конца поля — по кнопке очистки, по своей кнопке в слоте
			`clear` или по слоту `trailing`. Кнопка очистки стоит в ней первой,
			перед содержимым `trailing`.
		-->
		<div v-if="clearable || $slots.clear || $slots.trailing" class="s-input__trailing">
			<!--
				Кнопка очистки — по `clearable`, выключена вместе с полем.
				`readonly` её не гасит: select-only Select и есть `readonly`, а
				очистка там работает. Имя ядро собирает с именем поля
				(`clearAria`), очищает команда поля `clear`. Клик не всплывает:
				предок, который слушает клик по полю (select-only Select
				открывает по нему панель), его не получит.

				Своя кнопка — слот `clear`: заменяет встроенную целиком и
				рисуется, когда задана. Команду очистки получает в scope.

				У кнопки нет `view`: значения вида объявляет тема, и разметка
				библиотеки их не знает. Кнопку тема красит по контексту
				(`.s-input__clear`).
			-->
			<slot name="clear" :clear="ctrl.clear">
				<Button
					embedded="input.clear"
					v-if="clearable"
					class="s-input__clear"
					:size="size"
					:disabled="disabled"
					@click.stop="ctrl.clear()"
					v-bind="clearAria"
				>
					<Icon embedded="input.clear-icon" :tag="clearIconTag" :size="size" />
				</Button>
			</slot>
			<slot name="trailing" :ctrl="ctrl"> </slot>
		</div>
	</component>
</template>
