// packages/ui/angular/src/adapter/runtime/useAdapter.ts
/**
 * useAdapter — основной Angular runtime-слой (аналог useAdapter в React/Vue).
 *
 * Принимает ГОТОВЫЙ adapter-context и возвращает TBinding:
 *
 * - state: сигнал с текущими значениями props из Core
 * - syncInputs(inputs): Angular → Core (вызывается из ngOnChanges / ngOnInit)
 * - syncEvents(outputs): подписывает Angular EventEmitter'ы на Core-события
 * - bindElement(el): DOM-биндинг для TElementPlugin
 * - destroy(): очистка подписок + adapter.destroy()
 *
 * Состояние — сигнал, а не поле + markForCheck(): markForCheck помечает путь
 * грязным, но не планирует проверку, поэтому работал только благодаря Zone.js.
 * Сигнал уведомляет шаблон сам и одинаково работает в zone- и zoneless-режиме.
 */

import { computed, signal, type EventEmitter, type Signal } from '@angular/core'
import { TPluginsBindingExtension, toInstanceState } from '@soldy/setup'
import type { IAdapterContext, TInstanceState } from '@soldy/setup'
import { TElementPlugin } from '@soldy/plugins'
import type { IPluginBundle } from '@soldy/plugins'
import { createInspector } from '../common/createInspector'
import { buildInitialState, bindOutput, bindInput } from './useSyncProps'
import { bindEvents } from './useSyncEvents'

export type TBinding<TInstance = any> = {
	/** Свойства инстанса со снимком через `valueOf()` — см. `TInstanceState`. */
	readonly state: Signal<TInstanceState<TInstance>>
	readonly ctrl: TInstance
	readonly plugins: IPluginBundle | null
	syncInputs(inputs: object): void
	syncEvents(outputs: Record<string, EventEmitter<unknown>>): () => void
	bindElement(el: HTMLElement | null): void
	destroy(): void
}

export function useAdapter<TInstance extends object = object>(
	adapter: IAdapterContext<TInstance>,
): TBinding<TInstance> {
	const inspector = createInspector(adapter.accessor)
	const values = signal<Record<string, unknown>>(buildInitialState(adapter.accessor, inspector))

	const unbindOutput = bindOutput(adapter.accessor, inspector, (name, value) => {
		values.update((prev) => (Object.is(prev[name], value) ? prev : { ...prev, [name]: value }))
	})

	return {
		state: computed(() => toInstanceState<TInstance>(values())),

		ctrl: adapter.instance,
		plugins: adapter.bundle,

		syncInputs(inputs: object): void {
			bindInput(adapter.accessor, inspector, inputs)
		},

		syncEvents(outputs: Record<string, EventEmitter<unknown>>): () => void {
			return bindEvents(adapter.accessor, inspector, outputs)
		},

		bindElement(el: HTMLElement | null): void {
			const plugin = adapter.bundle?.get(TElementPlugin)

			if (plugin) {
				plugin.element = el
			} else {
				adapter.get(TPluginsBindingExtension)?.bindElement(el ?? null)
			}
		},

		destroy(): void {
			unbindOutput()
			adapter.destroy()
		},
	}
}

// packages/ui/solid/src/adapter/runtime/useAdapter.ts
/**
 * useAdapter — единственный Solid-хук на весь проект (аналог useAdapter
 * из Vue/React/Svelte-пакетов).
 *
 * Принимает ГОТОВЫЙ adapter-context (создаётся в setup-слое компонента через
 * createAdapterContext) и связывает его с Solid:
 *
 * 1. Core → Solid: подписка на триггеры props (bindOutput)
 * 2. Solid → Core: синхронизация входных props (bindInput)
 * 3. События (Core → колбэк-пропы onXxx)
 * 4. DOM-биндинг через callback-ref
 * 5. Очистка при уничтожении компонента (onCleanup)
 *
 * Props передаются как есть: в Solid это объект геттеров, деструктурировать
 * его нельзя, но читать напрямую — можно и нужно.
 */

import { createEffect, createMemo, onCleanup } from 'solid-js'
import { TPluginsBindingExtension, collectForwardProps, toInstanceState } from '@soldy/setup'
import type { IAdapterContext, TInstanceState } from '@soldy/setup'
import { TElementPlugin } from '@soldy/plugins'
import type { IPluginBundle } from '@soldy/plugins'
import { createInspector } from '../common'
import { useSyncProps } from './useSyncProps'
import { useSyncEvents } from './useSyncEvents'

export type TBinding<TInstance = object, TProps extends object = object> = {
	readonly ctrl: TInstance
	readonly plugins: IPluginBundle | null
	/** Свойства инстанса со снимком через `valueOf()` — см. `TInstanceState`. */
	readonly state: TInstanceState<TInstance>
	/** Мемо: DOM-атрибуты, не съеденные компонентом */
	forwardProps: () => Partial<TProps>
	/** callback-ref для корневого элемента */
	ref: (el: Element) => void
}

export function useAdapter<TProps extends object, TInstance extends object = object>(
	adapter: IAdapterContext<TInstance>,
	props: TProps,
): TBinding<TInstance, TProps> {
	const inspector = createInspector(adapter.accessor)

	// 1. Реактивность: Core ↔ Solid
	const { state, bindOutput, bindInput } = useSyncProps(adapter.accessor, inspector)

	// 1.1. Core → Solid: подписка на всё время жизни, отписка на onCleanup
	onCleanup(bindOutput())

	// 1.2. Solid → Core: эффект читает props, поэтому перезапускается при изменении
	createEffect(() => bindInput(props))

	// 2. События
	onCleanup(useSyncEvents(adapter.accessor, inspector, props))

	// 3. Очистка контекста
	onCleanup(() => adapter.destroy())

	const forwardProps = createMemo(() =>
		collectForwardProps(props, adapter, inspector, 'children'),
	)

	return {
		ctrl: adapter.instance,
		plugins: adapter.bundle,
		state: toInstanceState<TInstance>(state),
		forwardProps,

		ref(el: Element) {
			const plugin = adapter.bundle?.get(TElementPlugin)

			if (plugin) {
				plugin.element = el

				onCleanup(() => {
					plugin.element = null
				})

				return
			}

			const extension = adapter.get<TPluginsBindingExtension>(TPluginsBindingExtension)

			if (!extension) return

			extension.bindElement(el)

			onCleanup(() => extension.bindElement(null))
		},
	}
}
