// packages/ui/angular/demo/app/common/property-field.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

@Component({
	selector: 'demo-property-field',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<div class="property-field">
			<label class="property-field__label">{{ label }}:</label>
			<div class="property-field__control"><ng-content></ng-content></div>
		</div>
	`,
})
export class PropertyFieldComponent {
	@Input() label = ''
}

// packages/ui/react/demo/common/PropertyField.tsx
import type { ReactNode } from 'react'

type PropertyFieldProps = {
	label: string
	children: ReactNode
}

export default function PropertyField({ label, children }: PropertyFieldProps) {
	return (
		<div className="property-field">
			<label className="property-field__label">{label}:</label>
			<div className="property-field__control">{children}</div>
		</div>
	)
}
