// packages/ui/solid/demo/common/PropertyField.tsx
import type { JSX } from 'solid-js'

type PropertyFieldProps = {
	label: string
	children: JSX.Element
}

export default function PropertyField(props: PropertyFieldProps): JSX.Element {
	return (
		<div class="property-field">
			{/* span, а не label: контрол приходит как children, связать по `for` нечем */}
			<span class="property-field__label">{props.label}:</span>
			<div class="property-field__control">{props.children}</div>
		</div>
	)
}

// packages/ui/react/demo/common/PropertyField.tsx
import type { ReactNode } from 'react'

type PropertyFieldProps = {
	label: string
	children: ReactNode
}

export default function PropertyField({ label, children }: PropertyFieldProps) {
	return (
		<div className="property-field">
			<label className="property-field__label">{label}:</label>
			<div className="property-field__control">{children}</div>
		</div>
	)
}
