// packages/ui/vue/src/components/tabs/Tabs.vue
<script lang="ts">
import { TabsItem } from './item'
import SetupTabs from './setup.component'

export default { ...SetupTabs, components: { TabsItem } }
</script>

<template>
	<div ref="rootElement" v-if="rendered" v-show="visible" :class="classes" v-bind="attrs">
		<!--
			Набор `aria` владельца — это список табов: `role="tablist"` и
			`aria-orientation` пишет ядро, имя из `aria_label` — TAriaPlugin.
			Корень его не получает: там рядом со списком лежат панели.
		-->
		<div class="s-tabs__list" v-bind="aria">
			<div class="s-tabs__list--leading" v-if="$slots.leading">
				<slot name="leading"></slot>
			</div>
			<slot>
				<!--
					Слоты элементов статические и получают сам элемент через scope:
					динамические имена (`item:${value}:leading`) резолвит только Vue,
					в остальных пяти адаптерах они недостижимы. Адресация конкретного
					элемента — условием внутри слота по `item.value`.
				-->
				<TabsItem v-for="item in shown" :key="item.uid" :ctrl="item">
					<template #leading>
						<slot name="item-leading" :item="item" />
					</template>
					<template #default>
						<slot name="item" :item="item" />
					</template>
					<template #trailing>
						<slot name="item-trailing" :item="item" />
					</template>
				</TabsItem>
			</slot>
			<div class="s-tabs__list--trailing" v-if="$slots.trailing">
				<slot name="trailing"></slot>
			</div>
		</div>
		<slot name="content" />
	</div>
</template>

// packages/ui/react/src/components/tabs/Tabs.tsx
import type { ReactElement } from 'react'
import { Elevate, hasSlot, renderSlot, toAriaProps, toRootProps } from '../../adapter'
import { TabsItem } from './item'
import { useSetupTabs } from './setup.component'
import type { TabsProps } from './base.component'

/**
 * Tabs — набор табов: список (`s-tabs__list`) и панели рядом с ним.
 *
 * Набор `aria` владельца — это список табов: `role="tablist"` и
 * `aria-orientation` пишет ядро, имя из `aria_label` — `TAriaPlugin`. Корень
 * его не получает: рядом со списком там лежат панели. На корне — `attrs`,
 * как у Vue.
 *
 * Табы — дети (`<Tabs.Item>`), а без детей — `shown` коллекции, по `TabsItem`
 * на элемент. Слоты элементов статические и получают элемент через scope:
 * `item`, `item-leading`, `item-trailing`. Панели (`<Tabs.Content>`) — слот
 * `content`, вне списка: дети лежат внутри `[role=tablist]`, и панель там
 * оказалась бы в списке табов.
 *
 * Список и панели — в слое лифта набора (`Elevate`): таб, смонтированный
 * внутри, при коммите войдёт в его коллекцию, а панель найдёт свой таб в его
 * движке.
 */
export function Tabs(props: TabsProps): ReactElement | null {
	const { ref, forwardProps, state, layer } = useSetupTabs(props)

	const { rendered, shown, attrs, aria } = state

	if (!rendered) return null

	return (
		<div {...toRootProps(ref, state, [attrs], forwardProps)}>
			<Elevate layer={layer}>
				<div className="s-tabs__list" {...toAriaProps(aria)}>
					{hasSlot(props.leading) ? (
						<div className="s-tabs__list--leading">{renderSlot(props.leading)}</div>
					) : null}
					{hasSlot(props.children)
						? renderSlot(props.children)
						: shown?.map((item) => (
								<TabsItem
									key={item.uid}
									ctrl={item}
									leading={renderSlot(props['item-leading'], { item })}
									trailing={renderSlot(props['item-trailing'], { item })}
								>
									{renderSlot(props.item, { item })}
								</TabsItem>
							))}
					{hasSlot(props.trailing) ? (
						<div className="s-tabs__list--trailing">{renderSlot(props.trailing)}</div>
					) : null}
				</div>
				{renderSlot(props.content)}
			</Elevate>
		</div>
	)
}
