// packages/ui/solid/demo/App.tsx
import { Dynamic } from 'solid-js/web'
import { For, Show, createSignal, type JSX } from 'solid-js'
import EventLog from './common/EventLog'
import type { EventLogEntry } from './common/EventLog'
import ButtonPlayground from './playgrounds/Button'
import ComponentViewPlayground from './playgrounds/ComponentView'

type PlaygroundKey = 'component-view' | 'button'

const playgrounds: Record<PlaygroundKey, { component: any; label: string }> = {
	'component-view': { component: ComponentViewPlayground, label: 'ComponentView' },
	button: { component: ButtonPlayground, label: 'Button' },
}

export default function App(): JSX.Element {
	const [active, setActive] = createSignal<PlaygroundKey>('component-view')
	const [activeView, setActiveView] = createSignal<'sandbox' | 'logs'>('sandbox')
	const [eventLog, setEventLog] = createSignal<EventLogEntry[]>([])

	const handleLog = (entry: EventLogEntry) =>
		setEventLog((prev) => [entry, ...prev].slice(0, 200))

	return (
		<div class="pg-app">
			<div class="pg-app__nav">
				<button
					class="pg-app__nav-btn"
					classList={{ 'pg-app__nav-btn--active': activeView() === 'sandbox' }}
					onClick={() => setActiveView('sandbox')}
				>
					Sandbox
				</button>
				<button
					class="pg-app__nav-btn"
					classList={{ 'pg-app__nav-btn--active': activeView() === 'logs' }}
					onClick={() => setActiveView('logs')}
				>
					Logs ({eventLog().length})
				</button>
			</div>

			<div class="pg-app__layout">
				<aside class="pg-app__sidebar">
					<h3 class="pg-app__sidebar-title">Components</h3>
					<nav class="pg-app__menu">
						<For each={Object.entries(playgrounds)}>
							{([key, value]) => (
								<button
									class="pg-app__menu-item"
									classList={{ 'pg-app__menu-item--active': active() === key }}
									onClick={() => setActive(key as PlaygroundKey)}
								>
									{value.label}
								</button>
							)}
						</For>
					</nav>
				</aside>

				<main class="pg-app__main">
					<div class="pg-app__content">
						<Show
							when={activeView() === 'sandbox'}
							fallback={
								<div class="pg-app__logs">
									<EventLog events={eventLog()} onClear={() => setEventLog([])} />
								</div>
							}
						>
							<div class="pg-app__container">
								{/* Dynamic пересоздаёт playground при смене: у каждого свой core-инстанс */}
								<Dynamic component={playgrounds[active()].component} onLog={handleLog} />
							</div>
						</Show>
					</div>
				</main>
			</div>
		</div>
	)
}

// packages/ui/svelte/demo/App.svelte
<script lang="ts">
	import EventLog from './common/EventLog.svelte'
	import type { EventLogEntry } from './common/EventLog.svelte'
	import ButtonPlayground from './playgrounds/Button.svelte'
	import ComponentViewPlayground from './playgrounds/ComponentView.svelte'

	type PlaygroundKey = 'component-view' | 'button'

	const playgrounds = {
		'component-view': { component: ComponentViewPlayground, label: 'ComponentView' },
		button: { component: ButtonPlayground, label: 'Button' },
	} as const

	let active = $state<PlaygroundKey>('component-view')
	let activeView = $state<'sandbox' | 'logs'>('sandbox')
	let eventLog = $state<EventLogEntry[]>([])

	const Current = $derived(playgrounds[active]?.component)

	function handleLog(entry: EventLogEntry) {
		eventLog = [entry, ...eventLog].slice(0, 200)
	}
</script>

<div class="pg-app">
	<div class="pg-app__nav">
		<button
			class="pg-app__nav-btn"
			class:pg-app__nav-btn--active={activeView === 'sandbox'}
			onclick={() => (activeView = 'sandbox')}
		>
			Sandbox
		</button>
		<button
			class="pg-app__nav-btn"
			class:pg-app__nav-btn--active={activeView === 'logs'}
			onclick={() => (activeView = 'logs')}
		>
			Logs ({eventLog.length})
		</button>
	</div>

	<div class="pg-app__layout">
		<aside class="pg-app__sidebar">
			<h3 class="pg-app__sidebar-title">Components</h3>
			<nav class="pg-app__menu">
				{#each Object.entries(playgrounds) as [key, value] (key)}
					<button
						class="pg-app__menu-item"
						class:pg-app__menu-item--active={active === key}
						onclick={() => (active = key as PlaygroundKey)}
					>
						{value.label}
					</button>
				{/each}
			</nav>
		</aside>

		<main class="pg-app__main">
			<div class="pg-app__content">
				{#if activeView === 'sandbox'}
					{#if Current}
						<div class="pg-app__container">
							<!-- key: у каждого playground свой core-инстанс, при смене его надо пересоздать -->
							{#key active}
								<Current onLog={handleLog} />
							{/key}
						</div>
					{:else}
						<div class="pg-app__error">
							<div class="pg-app__error-content">
								<h1 class="pg-app__error-title">not found</h1>
								<p class="pg-app__error-text">Check the active variable</p>
							</div>
						</div>
					{/if}
				{:else}
					<div class="pg-app__logs">
						<EventLog events={eventLog} onClear={() => (eventLog = [])} />
					</div>
				{/if}
			</div>
		</main>
	</div>
</div>
