// packages/ui/react/src/components/list-box/item/Item.tsx
import type { ElementType, ReactElement } from 'react'
import {
	renderSlot,
	roleIcon,
	toAriaProps,
	toControlAttrs,
	toRootForward,
	toRootProps,
} from '../../../adapter'
import { Button } from '../../button'
import { Icon } from '../../icon'
import { useSetupListBoxItem } from './setup.component'
import type { ListBoxItemAttributes, ListBoxItemProps } from './base.component'

/**
 * ListBoxItem — элемент списка: корень по `tag` (по умолчанию `div`) и строка
 * внутри — `Button`, как у Vue.
 *
 * Наборы ядра стоят на двух элементах. Корень несёт `dataset`, `attrs` и место
 * в коллекции (`order`): тема читает `data-content-fit` с него. Строка несёт
 * `aria` и тот же `dataset` — выбор и подсветку тема красит на `.s-button`.
 * Атрибуты потребителя делятся так же, как у Vue: класс и стиль — корню,
 * остальное — строке, поверх её наборов: `tabindex="-1"` элемента перекрывает
 * `tabindex="0"`, который кнопка на `div` ставит себе сама.
 *
 * Тег строки фиксирован (`div`), а не берётся из `tag` элемента: `tag` — тег
 * корня, под фиксированный тег строки написан `TListBoxItem._ariaTag`.
 *
 * Клик выбирает через `adapters.list.choose()`, а не `selection.toggle()`:
 * выключенному элементу отказывает список, тем же путём, что и клавиатура.
 * Клик потребителя приходит после выбора — как у Vue, где слушатели
 * складываются.
 *
 * Обёртка отметки рисуется, пока `indicator` не `none`, — и у невыбранных
 * тоже: она резервирует место. Иконка внутри — только у выбранного, слот
 * `indicator-icon` подменяет её. `aria-hidden`: состояние скринридеру
 * объявляет `aria-selected`, второй источник того же факта дал бы двойное
 * объявление.
 */
export function ListBoxItem(props: ListBoxItemProps): ReactElement | null {
	const { ref, forwardProps, state, context } = useSetupListBoxItem(props)

	const {
		rendered,
		tag,
		text,
		view,
		disabled,
		size,
		variant,
		selected,
		indicator,
		aria,
		dataset,
		attrs,
	} = state

	if (!rendered) return null

	const Tag = tag as ElementType
	const chosen = selected ?? false
	const { onClick, ...row } = toControlAttrs<ListBoxItemAttributes>(forwardProps)

	const mark = (
		<span className="s-list-box-item__indicator" aria-hidden="true">
			{renderSlot(props['indicator-icon'], { selected: chosen }) ??
				(chosen ? (
					<Icon embedded="list-box.indicator" tag={roleIcon('check')} size={size} />
				) : null)}
		</span>
	)

	return (
		<Tag {...toRootProps(ref, state, [dataset, attrs], toRootForward(forwardProps))}>
			<Button
				embedded="list-box.row"
				tag="div"
				view={view}
				disabled={disabled}
				size={size}
				variant={variant}
				{...toAriaProps(aria)}
				{...toAriaProps(dataset)}
				{...row}
				onClick={(event) => {
					context?.adapters.list.choose()
					onClick?.(event)
				}}
				leading={
					<>
						{indicator === 'start' ? mark : null}
						{renderSlot(props.leading)}
					</>
				}
				trailing={
					<>
						{renderSlot(props.trailing)}
						{indicator === 'end' ? mark : null}
					</>
				}
			>
				{renderSlot(props.children, { text: text ?? '', selected: chosen }) ?? text}
			</Button>
		</Tag>
	)
}

// packages/ui/vue/src/components/list-box/item/Item.vue
<script lang="ts">
import { Icon } from '../../icon'
import { Button } from '../../button'
import SetupListBoxItem from './setup.component'

/**
 * Обёртка отметки рисуется, пока `indicator` не `none` — и у невыбранных тоже:
 * она резервирует место, иначе строка прыгала бы при выборе. Иконка внутри —
 * только у выбранного.
 *
 * Сторона логическая (`start`/`end`), поэтому в RTL отметка сама оказывается с
 * нужного края: `dir` стоит на корне элемента, а строка — flex.
 *
 * `aria-hidden`: отметка декоративна, состояние скринридеру объявляет
 * `aria-selected`. Два источника одного факта дали бы двойное объявление.
 */
export default { ...SetupListBoxItem, components: { Icon, Button } }
</script>

<template>
	<component
		ref="rootElement"
		:is="tag"
		v-if="rendered"
		v-show="visible"
		:class="classes"
		:style="{ order: order }"
		v-bind="{ ...dataset, ...containerAttrs, ...attrs }"
	>
		<!--
			`dataset` биндится дважды, и это не описка. Тема читает
			`data-content-fit` с обёртки, а `data-selected` / `data-highlighted`
			— с `.s-button`: у ListBox состояние размазано по двум элементам,
			в отличие от Select и Accordion, где всё на обёртке.

			Разложить набор в обе точки дешевле, чем переносить состояние: у
			`.s-button` подсветка и выбор раскрашены по вариантам, а у элемента
			списка своих таких правил нет. Приводить разметку к одному носителю
			— часть задачи про доступность ListBox, там же, где ему добавят
			`role="option"`; сейчас `aria-selected` всё ещё захардкожен здесь,
			а не приходит набором.

			Тег строки фиксирован (`tag="div"`), а не берётся из `tag` элемента:
			`tag` — тег корня (`TComponentView`), и рисует по нему корень
			`<component :is>` выше. Под фиксированный тег строки написан и
			`TListBoxItem._ariaTag` — он решает, писать ли `aria-disabled`.

			Клик выбирает через `adapters.list.choose()`, а не
			`selection.toggle()`: выключенному элементу отказывает список, тем же
			путём, что и Enter с пробелом у клавиатуры. `click`, а не
			`action:press`: у строки `tabindex="-1"`, фокус после клика остаётся
			на ней, и Enter дал бы два переключения — `press` строки и клавиатура
			корня.
		-->
		<Button
			embedded="list-box.row"
			tag="div"
			:view="view"
			:disabled="disabledResolved"
			:size="size"
			:variant="variant"
			:aria-selected="String(selected)"
			@click="context?.adapters.list.choose()"
			v-bind="{ ...aria, ...dataset, ...controlAttrs }"
		>
			<template #leading>
				<span
					v-if="indicator === 'start'"
					class="s-list-box-item__indicator"
					aria-hidden="true"
				>
					<slot name="indicator-icon" :selected="selected">
						<Icon
							embedded="list-box.indicator"
							v-if="selected"
							:tag="indicatorIconTag"
							:size="size"
						/>
					</slot>
				</span>
				<slot name="leading" />
			</template>

			<slot name="default" :text="text" :selected="selected">
				{{ text }}
			</slot>

			<template #trailing>
				<slot name="trailing" />
				<span
					v-if="indicator === 'end'"
					class="s-list-box-item__indicator"
					aria-hidden="true"
				>
					<slot name="indicator-icon" :selected="selected">
						<Icon
							embedded="list-box.indicator"
							v-if="selected"
							:tag="indicatorIconTag"
							:size="size"
						/>
					</slot>
				</span>
			</template>
		</Button>
	</component>
</template>
